server:
  port: 8080

spring:
  application:
    name: auth2-server
  redis:
    host: 127.0.0.1
    database: 0

application:
  init:
    users[0]:
      username: admin
      password: '{bcrypt}$2a$10$tMSDLeQjFehV8Z1BxoU3quISNyLXXMDI8pdA3RKdwqv1ujuZ6AAQG'
      authorities: admin
      roles: admin,test-admin
    users[1]:
      username: test-admin
      password: '{bcrypt}$2a$10$tMSDLeQjFehV8Z1BxoU3quISNyLXXMDI8pdA3RKdwqv1ujuZ6AAQG'
      authorities: admin
      roles: test-admin

eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
logging.level.org.springframework.security: info